services:
  # frontend:
  #   image: codefire-frontend
  #   container_name: codeFire-frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: frontend.dockerfile
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:4000
  #   restart: always
  #   depends_on:
  #     - backend
  backend:
    image: codefire-backend
    container_name: codeFire-backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
      - JUDGE0_URL=http://host.docker.internal:2358
    restart: always
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
